from docker.io/alpine:latest as builder

run apk add --no-cache git && git clone -b v0.9.0 --depth 1 https://codeberg.org/emersion/soju.git /src
run apk add --no-cache go gcc musl-dev sqlite-dev make
workdir /src
run CGO_ENABLED=1 GOFLAGS='-trimpath -tags=libsqlite3' make soju



from docker.io/alpine:latest
run apk add --no-cache sqlite sqlite-libs
copy --from=builder /src/soju /src/sojuctl /src/sojudb /bin
copy config /etc/soju/config
expose 6667

entrypoint ["soju"]
